In [1]:
def selection_sort(arr):
    n = len(arr)

    for i in range(n):
        
        min_index = i
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j

        
        arr[i], arr[min_index] = arr[min_index], arr[i]


my_list = [1,1,0,0,2,2,0,0,1,0,2,0,1]
selection_sort(my_list)
print("Sorted array is:", my_list)


Sorted array is: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]


In [10]:
def bubbleSort(arr):
    n = len(arr)
    
    for i in range(n):
        swapped = False
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                swapped = True
        if not swapped:
            break
            
arr = [1, 1, 0, 0, 2, 2, 0, 0,1,0,2,0,1]
bubbleSort(arr)

print("Sorted array:", arr)


Sorted array: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2]


In [12]:
def bubbleSort(name):
    name_list = list(name)
    n = len(name_list)
    
    for i in range(n):
        swapped = False
        
        for j in range(0, n-i-1):
            if name_list[j] > name_list[j+1]:
                name_list[j], name_list[j+1] = name_list[j+1], name_list[j]
                swapped = True
        
        if not swapped:
            break
    
    return ''.join(name_list)

name = "Punit Kumar Singh"
sorted_name = bubbleSort(name)
print("Sorted name:", sorted_name)


Sorted name:   KPSaghiimnnrtuu


In [13]:
def bubbleSort(name):
    name_list = list(name)
    n = len(name_list)
    
    for i in range(n):
        swapped = False
        
        for j in range(0, n-i-1):
            if name_list[j] > name_list[j+1]:
                name_list[j], name_list[j+1] = name_list[j+1], name_list[j]
                swapped = True
        
        if not swapped:
            break
    
    return ''.join(name_list)

name = "punit kumar singh"
sorted_name = bubbleSort(name)
print("Sorted name:", sorted_name)


Sorted name:   aghiikmnnprstuu


In [7]:
class Node:
    def __init__ (self, value):
        self.value = value
        self.next = None

def has_cycle(head):
    if head is None or head.next is None:
        return False  
    
    slow = head
    fast = head
    
    while fast is not None and fast.next is not None:
        slow = slow.next
        fast = fast.next.next
        
        if slow == fast:
            return True  
    
    return False

node1 = Node(1)
node2 = Node(2)
node3 = Node(3)
node4 = Node(4)

node1.next = node2
node2.next = node3
node3.next = node4
node4.next = node2


print(has_cycle(node1)) 


True


In [5]:
def remove_duplicates(input):
    if not input:
        return [] 

    unique = []

    for item in input:
        if item not in unique:
            unique.append(item)

    return unique

input = [1,12,11,10,11,1]
result = remove_duplicates(input)
print(result) 


[1, 12, 11, 10]


In [3]:
def is_palindrome(s):
    
    s = s.replace(" ", "").lower()
    
    return s == s[::-1]

input_string = "mom"
if is_palindrome(input_string):
    print(f"{input_string} is a palindrome.")
else:
    print(f"{input_string} is not a palindrome.")


mom is a palindrome.


In [40]:
matrix = np.array([[1, 3, 2], [9, 4, 12], [6, 8, 18]])
print(matrix)

matrix = np.where(matrix % 3 == 0)

print(multiples_of_3)

print(product_of_multiples)

is_greater_than_50 = product_of_multiples> 50

if is_greater_than_50:
    print("product is greater than 50.")
else:
    print("product is not greater than 50.")



[[ 1  3  2]
 [ 9  4 12]
 [ 6  8 18]]
[ 3  9 12  6 18]
34992
product is greater than 50.


In [57]:
import numpy as np

M1 = np.array([[2,-2,-4],
               [-1, 3, 4],
               [1, -2, -3]])

M2 = np.array([[2,-2,-4],
              [-1, 3, 4],
              [1, -2, -3]])

M = np.dot(matrix1, matrix2)


print("M*M=M")
print(M)


M*M=M
[[ 2 -2 -4]
 [-1  3  4]
 [ 1 -2 -3]]


In [61]:
original_matrix = [[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]

transposed_matrix = [[original_matrix[j][i] for j in range(len(original_matrix))] for i in range(len(original_matrix[0]))]

rotated_matrix = transposed_matrix[::-1]

for row in rotated_matrix:
    print(row)


[3, 6, 9]
[2, 5, 8]
[1, 4, 7]


In [3]:
def find_pairs(a):
    pairs = []
    for i in range(len(a)):
        for j in range(i + 1, len(a)):
            if a[i] > a[j]:
                pairs.append((a[i], a[j]))
    return pairs

a = [8, 9, 16, 1]
result = find_pairs(a)
      print(result)


[(8, 1), (9, 1), (16, 1)]


In [11]:
class TreeNode:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

def are_identical_trees(root1, root2):
    if root1 is None and root2 is None:
        return True
    if root1 is None or root2 is None:
        return False
    if root1.value != root2.value:
        return False
    
    left_identical = are_identical_trees(root1.left, root2.left)
    right_identical = are_identical_trees(root1.right, root2.right)
    
    return left_identical and right_identical

root1 = TreeNode(1)
root1.left = TreeNode(2)
root1.right = TreeNode(3)
root1.left.left = TreeNode(4)

root2 = TreeNode(1)
root2.left = TreeNode(2)
root2.right = TreeNode(3)
root2.left.left = TreeNode(6)

if are_identical_trees(root1, root2):
    print("The trees are identical.")
else:
    print("The trees are not identical.")


The trees are not identical.


In [13]:
def mirror_sentence(sentence):

    words = sentence.split()

    reversed_words = [word[::-1] for word in words]

    mirrored_sentence = ' '.join(reversed_words[::-1])

    return mirrored_sentence


original_sentence = "The sky is blue"
mirrored_sentence = mirror_sentence(original_sentence)
print(mirrored_sentence)


eulb si yks ehT


In [12]:
matrix = [
    [0, 0, 1, 0],
    [1, 1, 0, 1],
    [0, 0, 0, 0],
    [1, 1, 1, 1]
]

max_row = 1
max_ones = 1

for i in range(len(matrix)):
    ones_count = sum(matrix[i])
    if ones_count > max_ones:
        max_ones = ones_count
        max_row = i

print("Row with the most 1s is row", max_row)


Row with the most 1s is row 3


In [18]:
matrix = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
]

MR = len(matrix) // 2
MC= len(matrix[0]) // 2

MN = matrix[MR][MC]

MS = sum(matrix[MR]) + sum(row[MC] for row in matrix) - MN

matrix[MR][MC] = MS

for row in matrix:
    print(row)

[1, 2, 3, 4, 5]
[6, 7, 56, 9, 10]
[11, 12, 13, 14, 15]


In [22]:
import itertools
MATRIX = {'1':'00',
    '2': 'ABC',
    '3': 'DEF',
    '4': 'GHI',
    '5': 'JKL',
    '6': 'MNO',
    '7': 'PQR',
    '8': 'STU',
    '9': 'VWZ',
}

def number_to_letters(number):
    letters = []
    for digit in number:
        if digit in MATRIX:
            letters.append(MATRIX[digit])
    return letters

phone_number = input("Enter a phone number (digits only): ")

letters = number_to_letters(phone_number)

if letters:
    print("The corresponding letters for the phone number are:")
    for combination in itertools.product(*letters):
        print("".join(combination))
else:
    print("No valid letters found for the given phone number.")


Enter a phone number (digits only): 23
The corresponding letters for the phone number are:
AD
AE
AF
BD
BE
BF
CD
CE
CF


In [1]:
class TreeNode:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

def binary_tree():
    root = TreeNode(1)
    root.left = TreeNode(2)
    root.right = TreeNode(3)
    root.left.left = TreeNode(4)
    root.left.right = TreeNode(5)
    root.right.left = TreeNode(6)
    root.right.right = TreeNode(7)
    root.left.left.left = TreeNode(8)
    root.left.left.right = TreeNode(9)
    root.left.left.left.left = TreeNode(10)
    root.left.left.left.right = TreeNode(11)
    root.left.left.right.left = TreeNode(12)
    root.left.left.right.right = TreeNode(13)
    root.left.left.left.right.right = TreeNode(14)
    root.left.left.left.right.right.right = TreeNode(15)
    return root

print (binary_tree)

<function binary_tree at 0x0000021BB0E4A700>


In [2]:
def update_boundary_to_1(matrix):
    if not matrix:
        return matrix
    
    num_rows = len(matrix)
    num_cols = len(matrix[0])

    for i in range(num_cols):
        matrix[0][i] = 1
        matrix[num_rows - 1][i] = 1

    for i in range(1, num_rows - 1):
        matrix[i][0] = 1
        matrix[i][num_cols - 1] = 1

    return matrix

# Input matrix
matrix = [
    [0, 1, 1, 1],
    [1, 1, 0, 1],
    [1, 0, 0, 1]
]

updated_matrix = update_boundary_to_1(matrix)

for row in updated_matrix:
    print(row)


[1, 1, 1, 1]
[1, 1, 0, 1]
[1, 1, 1, 1]
